name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: npm Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '16.x'

      - name: Install npm dependencies
        run: npm ci --prefer-offline --cache=./.npm

      - name: Build library
        run: npx tsc --outDir .

      - name: Set npm credentials
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Set version in package.json
        run: npm --no-git-tag-version version ${{ github.event.release.tag_name }}

      - name: Publish to npm Registry
        run: npm publish --access public
